title: Bianca Pereira
description: Website

url: http://bianca-pereira.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Blog
   url: /blog
 - title: Publications
   url: /publications.html
 - title: Contact
   url: /contact.html

social:
   github: bianca-pereira
   twitter: bianca_oli_per
   facebook: Bianca-Pereira-978301655573527
   email: bianca@biancapereira.me
   linkedin: biancaolipereira
   soundcloud: user-671615919
   quora: Bianca-Pereira-7

google_analytics: "UA-66654253-1"

scholar:
  style: assets/bibliography/apa-no-doi-no-issue.csl
  locale: en

  sort_by: year
  order: descending

  source: assets/bibliography
  bibliography: references.bib
  bibliography_template: bibtemplate
#  bibliography_template: "{{ reference | replace_first: 'Pereira, B.', '<b>Pereira, B.</b>' }} {% if entry.pdf-file %}[<a href='{{entry.pdf-file}}'>pdf-file</a>]{% endif %} [<a data-toggle='collapse' href='#{{key}}-bibtex'>BibTeX</a>] <pre id='{{key}}-bibtex' class='pre pre-scrollable collapse'>{{entry.bibtex}}</pre>"

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"


